-- Create database
CREATE DATABASE IF NOT EXISTS creator_tracker;
USE creator_tracker;

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Creators table
CREATE TABLE IF NOT EXISTS creators (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE,
  phone VARCHAR(20),
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Performance logs table
CREATE TABLE IF NOT EXISTS performance_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  creator_id INT NOT NULL,
  provided_link TEXT,
  posted_link TEXT,
  views_count INT DEFAULT 0,
  date_logged TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE
);

-- Insert default admin user (password: admin123)
-- Hash will be generated by the application
